# Generated by Django 4.0 on 2023-10-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdata_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
