# Generated by Django 4.2.6 on 2023-10-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdata_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='nickname',
        ),
    ]
