# Generated by Django 4.0 on 2023-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_userdata_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
